noun = input("Enter a noun:")
verb =  input("Enter a verb:")
adjective =  input("Enter an adjective:")
place = input("Enter a place:")
print(f"The {adjective} {noun} {verb} the ancient temple in  {place}")